defaults: &defaults
  adapter: mysql2
  host: 127.0.0.1
  pool: 25
  username: username
  password: passowrd

development:
  <<: *defaults
  database: db_dev

test: &test
  <<: *defaults
  database: db_test

production:
  uri: <%= ENV['DATABASE_URL'] %>
